version: '3.8'

services:

  nest-js:
    container_name: ${NAME}-nest-js
    build: .
    image: nest-i
    ports:
      - "${NEST_PORT}:3000"
    volumes:
      - .:/src
    command: "npm run start:dev"
    depends_on:
      - db
  
  db:
    container_name: ${NAME}-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -p ${DB_PORT}
    ports:
        - "5432:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db